FROM node:20.14-bullseye as builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM node:20.14-bullseye

WORKDIR /app

RUN apk update

COPY package.json .

RUN npm install --only=prod

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["npm", "run", "start:prod"]