FROM node:20.14-bullseye as builder

WORKDIR /app

COPY packages/frontend/package*.json ./

RUN npm install
COPY packages/frontend .

RUN npm run build --prod

FROM nginx:alpine
COPY --from=builder /app/dist/app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]