name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: [frontend, backend]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push Docker image to GHCR
      env:
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/catmash-${{ matrix.package }}:latest
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker build -t $IMAGE_NAME -f docker/Dockerfile.${{ matrix.package }} .
        docker push $IMAGE_NAME

    - name: Deploy notification
      env:
        DEPLOY_WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}-${{ matrix.package }}
      run: |
        curl -X GET $DEPLOY_WEBHOOK_URL -H 'Content-type: application/json' --data '{"text":"Deployment completed successfully."}'
