name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14'

    - name: Install dependencies
      run: npm install
      
    - name: Build with Lerna
      run: |
        npx lerna run build

    - name: Build and push Docker image to GHCR
      env:
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/catmash-app:latest
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker build -t $IMAGE_NAME -f docker/Dockerfile .
        docker push $IMAGE_NAME

    - name: Deploy notification
      env:
        DEPLOY_WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
      run: |
        curl -X POST $DEPLOY_WEBHOOK_URL -H 'Content-type: application/json' --data '{"text":"Deployment completed successfully."}'